### PR TITLE
Migrate to GitHub Actions.

### LINKED ISSUE #329: Move away from Travis for CI
Unfortunately, Travis recently change its policy wrt open source software and test results can take several days to finish. We could move to Github Actions.

### PR DESCRIPTION
**Pull request by jezdez**
Travis CI has a new pricing model which places limits on open source.

* https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
* https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

Many projects are moving to GitHub Actions instead, including Jazzband projects:

* https://github.com/orgs/jazzband/projects/1
* https://github.com/jazzband-roadies/help/issues/206

This is based on https://github.com/jazzband/contextlib2/pull/26.

Fix #329.

TODO:

* [x] @jezdez to add `JAZZBAND_RELEASE_KEY` to the repo secrets.

### CODE REVIEW

**Review by Natim — APPROVED** [review]

**Comment by Natim** [comment]
I'm currious of why removing the Makefile though?

**Comment by jezdez** [comment]
> I'm currious of why removing the Makefile though?

Not a huge reason other than Makefiles tend to collect dust and it doesn't map to the tox config as nicely, adding duplication. I can re-add it though, no strong feelings other than "let's get this migrated".

**Comment by jezdez** [comment]
@Natim I've added a separate workflow for running pre-commit but wondered if you'd be interested in trialing the use of https://pre-commit.ci?

**Review by claudep — APPROVED** [review]
Thanks a lot for working on this. I'm not yet familiar with GH actions, so I'm mostly trusting you!

**Comment by jezdez** [comment]
> Thanks a lot for working on this. I'm not yet familiar with GH actions, so I'm mostly trusting you!

Thank you, this is a pretty conservative way to do GitHub Actions, and we have now ~40 other Jazzband projects doing a very similar setup. I'm a bit mote skeptical to have a 3rd party service for pre-commit (since it's what has screwed us with Travis CI), but since it's from the pre-commit author I think it may be worth a shot.

**Pull request merged**
